[package]
name = "fpc_test_target"
type = "contract"
compiler_version = ">=1.0.0"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/aztec-labs-eng/aztec-nr", tag = "v5.0.1", directory = "aztec" }
